dist: trusty

language: cpp

matrix:
  include:
    # Ubuntu 16.04 LTS-compatible gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CXX=g++-5"

    # Ubuntu 16.04 LTS-compatible clang
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"

script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="${CXX}"
  - make -j ${JOBS}
  - tests/run_unittests
