dist: trusty

language: cpp

matrix:
  include:
    # Ubuntu 16.04 LTS-compatible gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - M_CXX=g++-5

    # Ubuntu 16.04 LTS-compatible clang
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-3.8
            - libc++-dev
      env:
        - M_CXX=clang++-3.8
        - M_CXXFLAGS="-stdlib=libc++"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="${M_CXX}" -DCMAKE_CXX_FLAGS="${M_CXXFLAGS}"
  - make -j ${JOBS}
  - tests/run_unittests
