dist: trusty

language: cpp

matrix:
  include:
    # Ubuntu 16.04 LTS-compatible gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CXX=g++-5

    # Ubuntu 16.04 LTS-compatible clang
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - CXX=clang++-3.8
        - CXXFLAGS="-stdlib=libc++"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="${CXX}" -DCMAKE_CXX_FLAGS="${CXXFLAGS}"
  - make -j ${JOBS}
  - tests/run_unittests
